default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: batata
  username: postgres
  password: admin

test:
  <<: *default
  database: batata
  username: postgres
  password: admin

production:
  <<: *default
