# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b53eff7dedd547473b5dc242144ef3db2f31a0b67e7c2347fa5e8d01242a35c98eec2ac15d84da62c967b4922c0904740594eab8a14d52067adda0b3050c7b3d

test:
  secret_key_base: 04bff26e162eb198dd99e08f8876148cb8f483c8caabc2c4572ece244e411971af3d6612d80bf4c4e78d3f699634bf16b91c75996fde1dd5e4b7eb8bcab00481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
